on: 
  push:
    branches:
      - main
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.reactheme.com
        username: test@reactheme.com
        password: test@123!!
        protocol: ftps
        port: 21 # todo replace with your web hosts ftps port
        server-dir: /public_html/test/